before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended
script:
- mkdir _build
- latexmk -pdf -outdir=_build senior_thesis_proposal.tex
deploy:
  provider: releases
  api_key:
    secure: erkLJ5Z4K4sDwz6IvGJt2913zssIp5kFJDYCaB7nbiN2E48EpZurrJVSvXE4bL2zNTCIHMqUqJ9ltSnko5D0qjplxZvrd4bzzbI0QGFbBVLYtwRxVef6xLuDXnbCdXhORsEHm+US1WOscdzrJXyw5LO9l8iCo2ditB9Fdv/egQjhc+mt2BSxvokalsd5Q2SkuvPc1ARvaNuGyiL5rYUJXmHkI/oj2lfywX2if8JVZKYHvYhjfKKhobyHRnSidGVNlcK2wYTPKybD6FfmPBuGgVEI3QdCHB6v/wa/MkLL8Xl/rlmrhlB7fGMArH484c2qK/JlzicbiSVk69KLE/lJnS/yJg4QripizIT0TaKB61b7+9SK/5VayqZylWyiJeyBIlqeORsaVoaEQR0hhBkeN/ANAtPoIAj0zXBZ5xAt+13TgZqK81zkodTtF68vE0in+HMSmlisS/Iuuw3UHTugYaxfs4ejLYoC8pfb7vcbQ0EhHWMqSrOD6OUNV70xXsbjiqOL9FgzBJ8rih98DyV6aEBsi7Ohf6qqBpDzsRwqLe430tryadQxCfnAzV+Ofcw/B1OpB2DmtKIvq1p/LWtSQ/GsPISMxi8Lf7dJFh/lELJZhADjgSXxeet4SqWLlr+JPICL+hdd/XGYHUeLnjqebLC2k97oWKUe8WPrMszSY/0=
  file: _build/senior_thesis_proposal.pdf
  skip_cleanup: true
  on:
    tags: true
